name: Update Figma Preview

on:
  schedule:
    - cron: "0 0 * * *" # Chạy hàng ngày
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  update-preview:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Fetch Figma Preview
      env:
        FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
      run: python fetch_figma_preview.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add preview.png
        git commit -m "Update Figma preview"
        git push
